### ISSUE TITLE
mvn clean install fails - missing files?

### ISSUE THREAD

**Issue by helenhanks** [celestial-winter/vics#1]
ubuntu@ip-172-31-40-148:/git/vics$ mvn clean install
[INFO] Scanning for projects...
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Build Order:
[INFO] 
[INFO] webapp
[INFO] common
[INFO] paf-client
[INFO] paf-stub
[INFO] tools
[INFO] web-client
[INFO] web-server
[INFO]                                                                         
[INFO] ------------------------------------------------------------------------
[INFO] Building webapp 0.0.1
[INFO] ------------------------------------------------------------------------
[INFO] 
[INFO] --- maven-clean-plugin:2.5:clean (default-clean) @ webapp ---
[INFO] 
[INFO] --- maven-clean-plugin:2.5:clean (auto-clean) @ webapp ---
[INFO] 
[INFO] --- maven-enforcer-plugin:1.4.1:enforce (enforce) @ webapp ---
[INFO] 
[INFO] --- maven-source-plugin:2.4:jar-no-fork (attach-sources) @ webapp ---
[INFO] 
[INFO] --- maven-install-plugin:2.5.2:install (default-install) @ webapp ---
[INFO] Installing /git/vics/pom.xml to /home/ubuntu/.m2/repository/com/infinityworks/webapp/0.0.1/webapp-0.0.1.pom
[INFO]                                                                         
[INFO] ------------------------------------------------------------------------
[INFO] Building common 0.0.1
[INFO] ------------------------------------------------------------------------
[INFO] 
[INFO] --- maven-clean-plugin:2.5:clean (default-clean) @ common ---
[INFO] 
[INFO] --- maven-clean-plugin:2.5:clean (auto-clean) @ common ---
[INFO] 
[INFO] --- maven-resources-plugin:2.6:resources (default-resources) @ common ---
[INFO] Using 'UTF-8' encoding to copy filtered resources.
[INFO] skip non existing resourceDirectory /git/vics/common/src/main/resources
[INFO] 
[INFO] --- maven-compiler-plugin:3.3:compile (default-compile) @ common ---
[INFO] Compiling 4 source files to /git/vics/common/target/classes
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary:
[INFO] 
[INFO] webapp ............................................. SUCCESS [  2.131 s]
[INFO] common ............................................. FAILURE [  0.581 s]
[INFO] paf-client ......................................... SKIPPED
[INFO] paf-stub ........................................... SKIPPED
[INFO] tools .............................................. SKIPPED
[INFO] web-client ......................................... SKIPPED
[INFO] web-server ......................................... SKIPPED
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 3.524 s
[INFO] Finished at: 2016-11-06T16:55:57+00:00
[INFO] Final Memory: 15M/39M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.3:compile (default-compile) on project common: Fatal error compiling: directory not found: /git/vics/common/target/classes -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoExecutionException
[ERROR] 
[ERROR] After correcting the problems, you can resume the build with the command
[ERROR]   mvn <goals> -rf :common

**Comment by helenhanks** [comment]
Full details of how I set up the server and tried to build this are [here](https://drive.google.com/open?id=1ZCns8bVKtyMn0jY5G7VRxZzTWTx8iOWXznU4j_LFIZU).

**Comment by danielhjames** [comment]
Hi Helen, I noticed the line which says 'Compiling 4 source files to /git/vics/common/target/classes' so did you try creating this directory in the source tree and building again?

**Comment by helenhanks** [comment]
Hi Daniel, 

I tried reinstalling java, rebooting the server and a couple of other things. 

When I look for that directory, I notice it exists now. When I run the mvn clean install I have a slightly different message now. This time it is failing to delete something.

Regards,
Helen

ubuntu@ip-172-31-40-148:/git/vics$ mvn clean install 

[INFO] Scanning for projects...

[INFO] ------------------------------------------------------------------------

[INFO] Reactor Build Order:

[INFO]

[INFO] webapp

[INFO] common

[INFO] paf-client

[INFO] paf-stub

[INFO] tools

[INFO] web-client

[INFO] web-server

[INFO]

[INFO] ------------------------------------------------------------------------

[INFO] Building webapp 0.0.1

[INFO] ------------------------------------------------------------------------

[INFO]

[INFO] --- maven-clean-plugin:2.5:clean (default-clean) @ webapp ---

[INFO]

[INFO] --- maven-clean-plugin:2.5:clean (auto-clean) @ webapp ---

[INFO]

[INFO] --- maven-enforcer-plugin:1.4.1:enforce (enforce) @ webapp ---

[INFO]

[INFO] --- maven-source-plugin:2.4:jar-no-fork (attach-sources) @ webapp ---

[INFO]

[INFO] --- maven-install-plugin:2.5.2:install (default-install) @ webapp ---

[INFO] Installing /git/vics/pom.xml to /home/ubuntu/.m2/repository/com/infinityworks/webapp/0.0.1/webapp-0.0.1.pom

[INFO]

[INFO] ------------------------------------------------------------------------

[INFO] Building common 0.0.1

[INFO] ------------------------------------------------------------------------

[INFO]

[INFO] --- maven-clean-plugin:2.5:clean (default-clean) @ common ---

[INFO] Deleting /git/vics/common/target

[INFO] ------------------------------------------------------------------------

[INFO] Reactor Summary:

[INFO]

[INFO] webapp ............................................. SUCCESS [  2.364 s]

[INFO] common ............................................. FAILURE [  1.173 s]

[INFO] paf-client ......................................... SKIPPED

[INFO] paf-stub ........................................... SKIPPED

[INFO] tools .............................................. SKIPPED

[INFO] web-client ......................................... SKIPPED

[INFO] web-server ......................................... SKIPPED

[INFO] ------------------------------------------------------------------------

[INFO] BUILD FAILURE

[INFO] ------------------------------------------------------------------------

[INFO] Total time: 4.371 s

[INFO] Finished at: 2016-11-10T13:02:39+00:00

[INFO] Final Memory: 15M/37M

[INFO] ------------------------------------------------------------------------

[ERROR] Failed to execute goal org.apache.maven.plugins:maven-clean-plugin:2.5:clean (default-clean) on project common: Failed to clean project: Failed to delete /git/vics/common/target/test-classes/com/infinityworks/common/lang/TryTest.class -&gt; [Help 1]

[ERROR]

[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.

[ERROR] Re-run Maven using the -X switch to enable full debug logging.

[ERROR]

[ERROR] For more information about the errors and possible solutions, please read the following articles:

[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoExecutionException

[ERROR]

[ERROR] After correcting the problems, you can resume the build with the command

[ERROR]   mvn &lt;goals&gt; -rf :common

Sent using Zoho Mail

---- On Thu, 10 Nov 2016 12:57:14 +0000Daniel James &lt;notifications@github.com&gt; wrote ----

Hi Helen, I noticed the line which says 'Compiling 4 source files to /git/vics/common/target/classes' so did you try creating this directory in the source tree and building again?

**Comment by danielhjames** [comment]
The 'mvn clean install' command is intended to delete your previous compilation before compiling again. If the file /git/vics/common/target/test-classes/com/infinityworks/common/lang/TryTest.class exists, it may be in use by some process, such as the vics built-in web server. Try stopping the web server process, deleting and recreating the /git/vics/common/target/ directory and running simply 'mvn install'.

**Comment by varahamihira** [comment]
I think what Daniel said is most likely. I ran the build following the instructions and didn't see the described issues.
