### ISSUE TITLE
SQL file exposes personal information of real people?

### ISSUE THREAD

**Issue by danielhjames** [celestial-winter/vics#3]
See https://github.com/celestial-winter/vics/blob/master/web-server/src/test/resources/sql/users.sql

**Comment by danielhjames** [comment]
Well, maybe these aren't their real email addresses, but there are real people with these names. Could be more secure!

**Comment by varahamihira** [comment]
Thanks Daniel. They are made up names and email addresses. Sure there might be people with these names but this is common when using a data generator.

**Comment by danielhjames** [comment]
My suggestion would be to put a wrapper script around web-server/src/test/resources/sql/drop-create.sql which would accept arguments setting user account details, including password. The web server could then be installed non-interactively and be more secure by default.

**Comment by varahamihira** [comment]
Hi Daniel. This data is for automated tests only (not for production). Any production account setup is out of scope here. I think the proper long term solution would be to replace the auth model with a managed service (e.g. Auth0) and administer accounts that way. The current implementation was simple and worked for a small/short duration project. I am not planning to maintain this project and I recommend that it is forked. Thanks

**Comment by danielhjames** [comment]
Thanks for the explanation :-)
